<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-7A9FBF0" failures="1" tests="1" name="Test(failed)" time="0.254" errors="0" timestamp="2024-07-04T10:56:08 BST">
  <testcase classname="TestNG.Example9_Sample1" name="TC1" time="0.063">
    <failure type="java.lang.AssertionError" message="Failed TC1: both results are diff expected [Hello] but found [HI]">
      <![CDATA[java.lang.AssertionError: Failed TC1: both results are diff expected [Hello] but found [HI]
at TestNG.Example9_Sample1.TC1(Example9_Sample1.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- TC1 -->
  <testcase classname="TestNG.Example9_Sample1" name="TC2" time="0.0">
    <ignored/>
  </testcase> <!-- TC2 -->
  <testcase classname="TestNG.Example9_Sample1" name="TC3" time="0.0">
    <ignored/>
  </testcase> <!-- TC3 -->
</testsuite> <!-- Test(failed) -->
